-- MySQL Script generated by MySQL Workbench
-- Sat Nov 17 10:51:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trace
-- -----------------------------------------------------
-- 追溯系统表

-- -----------------------------------------------------
-- Schema trace
--
-- 追溯系统表
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trace` DEFAULT CHARACTER SET utf8 ;
USE `trace` ;

-- -----------------------------------------------------
-- Table `trace`.`trace_barcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_barcode` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `barcode` VARCHAR(200) NOT NULL COMMENT '条码值',
  `barcode_type` TINYINT UNSIGNED NULL COMMENT '条码类型',
  `barcode_source` TINYINT UNSIGNED NULL COMMENT '条码来源',
  `quality_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '品质',
  `quantity` DECIMAL(12,4) NOT NULL COMMENT '数量',
  `capacity` DECIMAL(12,4) NULL COMMENT '容量',
  `state` TINYINT UNSIGNED NULL COMMENT '条码状态',
  `batch_no` VARCHAR(100) NULL COMMENT '批次号',
  `wo_code` VARCHAR(64) NULL COMMENT '工单号\n',
  `material_id` INT NULL COMMENT '物料id',
  `process_id` INT NULL COMMENT '工序id',
  `equipment_id` INT NULL COMMENT '设备id',
  `effective_time` DATETIME NULL COMMENT '生效时间',
  `expiry_time` DATETIME NULL COMMENT '失效时间',
  `is_full` TINYINT UNSIGNED NULL COMMENT '是否满容量',
  `process_uuid` VARCHAR(36) NULL COMMENT '批处理id',
  `trace_attr` JSON NULL COMMENT '自定义属性',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '删除标记',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `barcode_UNIQUE` (`barcode` ASC))
ENGINE = InnoDB
COMMENT = '标识信息表';


-- -----------------------------------------------------
-- Table `trace`.`trace_material_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_material_pool` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `operation_id` BIGINT NOT NULL COMMENT '业务操作id',
  `quantity` DECIMAL(12,4) NULL COMMENT '数量',
  `remain_qty` DECIMAL(12,4) NULL COMMENT '剩余量',
  `deduction_count` SMALLINT NULL COMMENT '扣减次数',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
COMMENT = '物料池';


-- -----------------------------------------------------
-- Table `trace`.`trace_input_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_input_detail` (
  `id` BIGINT NOT NULL COMMENT 'uuid',
  `factory_id` INT NULL COMMENT '工厂id',
  `barcode` VARCHAR(200) NOT NULL COMMENT '投料标识',
  `op_type` TINYINT UNSIGNED NULL COMMENT '操作类型',
  `quality_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '品质',
  `quantity` DECIMAL(12,4) NOT NULL COMMENT '数量',
  `happen_time` DATETIME NULL COMMENT '投料时间',
  `batch_no` VARCHAR(100) NULL COMMENT '批次号',
  `wo_code` VARCHAR(64) NULL COMMENT '工单号\n',
  `shift_name` VARCHAR(256) NULL COMMENT '班次',
  `material_id` INT NULL COMMENT '物料id',
  `material_code` VARCHAR(64) NULL COMMENT '物料编码',
  `material_name` VARCHAR(64) NULL COMMENT '物料名称',
  `material_spec` VARCHAR(64) NULL COMMENT '物料规格\n',
  `material_unit` VARCHAR(64) NULL COMMENT '物料单位',
  `person_code` VARCHAR(64) NULL COMMENT '人员编码',
  `person_name` VARCHAR(64) NULL COMMENT '人员名称',
  `process_id` INT NULL COMMENT '工序id',
  `process_code` VARCHAR(64) NULL COMMENT '工序编码\n',
  `process_name` VARCHAR(64) NULL COMMENT '工序名称\n',
  `equipment_id` INT NULL COMMENT '设备id',
  `equipment_code` VARCHAR(256) NULL COMMENT '设备编码',
  `equipment_name` VARCHAR(256) NULL COMMENT '设备名称',
  `effective_time` DATETIME NULL COMMENT '生效时间',
  `expiry_time` DATETIME NULL COMMENT '失效时间',
  `process_uuid` VARCHAR(36) NULL COMMENT '批处理id',
  `parent_barcode` VARCHAR(200) NULL COMMENT '父标识',
  `trace_attr` JSON NULL COMMENT '自定义属性',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '投料记录表';


-- -----------------------------------------------------
-- Table `trace`.`trace_ouput_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_ouput_detail` (
  `id` BIGINT NOT NULL COMMENT 'uuid',
  `factory_id` INT NULL COMMENT '工厂id',
  `barcode` VARCHAR(200) NOT NULL COMMENT '产出标识',
  `op_type` TINYINT UNSIGNED NULL COMMENT '操作类型',
  `quality_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '品质',
  `quantity` DECIMAL(12,4) NOT NULL COMMENT '数量',
  `happen_time` DATETIME NULL COMMENT '产出时间',
  `batch_no` VARCHAR(100) NULL COMMENT '批次号',
  `wo_code` VARCHAR(64) NULL COMMENT '工单号\n',
  `shift_name` VARCHAR(256) NULL COMMENT '班次',
  `material_id` INT NULL COMMENT '物料id',
  `material_code` VARCHAR(64) NULL COMMENT '物料编码',
  `material_name` VARCHAR(64) NULL COMMENT '物料名称',
  `material_spec` VARCHAR(64) NULL COMMENT '物料规格\n',
  `material_unit` VARCHAR(64) NULL COMMENT '物料单位',
  `person_code` VARCHAR(64) NULL COMMENT '人员编码',
  `person_name` VARCHAR(64) NULL COMMENT '人员名称',
  `process_id` INT NULL COMMENT '工序id',
  `process_code` VARCHAR(64) NULL COMMENT '工序编码\n',
  `process_name` VARCHAR(64) NULL COMMENT '工序名称\n',
  `equipment_id` INT NULL COMMENT '设备id',
  `equipment_code` VARCHAR(256) NULL COMMENT '设备编码',
  `equipment_name` VARCHAR(256) NULL COMMENT '设备名称',
  `effective_time` DATETIME NULL COMMENT '生效时间',
  `expiry_time` DATETIME NULL COMMENT '失效时间',
  `process_uuid` VARCHAR(36) NULL COMMENT '批处理id',
  `defect_name` VARCHAR(64) NULL COMMENT '不合格原因',
  `parent_barcode` VARCHAR(200) NULL COMMENT '父标识',
  `trace_attr` JSON NULL COMMENT '自定义属性',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '产出记录表';


-- -----------------------------------------------------
-- Table `trace`.`trace_input_pool`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_input_pool` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'uuid',
  `factory_id` INT NULL COMMENT '工厂id',
  `barcode` VARCHAR(200) NOT NULL COMMENT '投料标识',
  `op_type` TINYINT UNSIGNED NOT NULL COMMENT '操作类型',
  `quality_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '品质',
  `quantity` DECIMAL(12,4) NOT NULL COMMENT '数量',
  `remain_qty` DECIMAL(12,4) NOT NULL COMMENT '剩余量',
  `happen_time` DATETIME NULL COMMENT '投料时间',
  `material_id` INT NOT NULL COMMENT '物料id',
  `material_code` VARCHAR(64) NULL COMMENT '物料编码',
  `material_name` VARCHAR(64) NULL COMMENT '物料名称',
  `material_spec` VARCHAR(64) NULL COMMENT '物料规格',
  `material_unit` VARCHAR(64) NULL COMMENT '物料单位',
  `batch_no` VARCHAR(100) NULL COMMENT '批次号',
  `wo_code` VARCHAR(64) NULL COMMENT '工单号\n',
  `last_wo_code` INT NULL COMMENT '上次产出工单',
  `process_id` INT NULL COMMENT '工序id',
  `last_process_id` INT NULL COMMENT '上次产出工序id',
  `equipment_id` INT NULL COMMENT '设备id',
  `last_equipment_id` INT NULL COMMENT '上次产出设备id',
  `process_uuid` VARCHAR(36) NULL COMMENT '批处理id',
  `parent_barcode` VARCHAR(200) NULL COMMENT '父标识',
  `trace_attr` JSON NULL COMMENT '自定义属性',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '投料池';


-- -----------------------------------------------------
-- Table `trace`.`trace_barcode_ext_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_barcode_ext_rule` (
  `id` INT NOT NULL COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `rule_name` VARCHAR(64) NULL COMMENT '规则名称',
  `description` VARCHAR(200) NULL COMMENT '规则描述',
  `test_sample` VARCHAR(200) NULL COMMENT '测试标识',
  `rule_script` TEXT NULL COMMENT 'js规则脚本',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`))
COMMENT = '外部标识解析规则';


-- -----------------------------------------------------
-- Table `trace`.`trace_barcode_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_barcode_relation` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `barcode` VARCHAR(200) NOT NULL COMMENT '子标识',
  `parent_barcode` VARCHAR(200) NOT NULL COMMENT '父标识',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
COMMENT = '标识父子关系表';


-- -----------------------------------------------------
-- Table `trace`.`trace_op_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_op_type` (
  `op_type` TINYINT UNSIGNED NOT NULL COMMENT '操作类型',
  `op_type_name` VARCHAR(64) NULL COMMENT '操作类型名称',
  `description` VARCHAR(200) NULL COMMENT '描述',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`op_type`))
COMMENT = '操作类型定义表';


-- -----------------------------------------------------
-- Table `trace`.`trace_app_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_app_config` (
  `id` INT NOT NULL COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `config_name` VARCHAR(64) NULL COMMENT '配置名称',
  `description` VARCHAR(64) NULL COMMENT '描述',
  `process_id` JSON NOT NULL COMMENT '工序id',
  `equipment_id` JSON NULL COMMENT '设备id',
  `process_config` JSON NULL COMMENT '工序配置',
  `input_config` JSON NULL COMMENT '投料配置',
  `output_config` JSON NULL COMMENT '产出行为配置',
  `output_material_config` JSON NULL COMMENT '产出物料配置',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '删除标记\n',
  PRIMARY KEY (`id`))
COMMENT = '追溯应用配置表';


-- -----------------------------------------------------
-- Table `trace`.`trace_attr_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_attr_config` (
  `factory_id` INT NULL COMMENT '工厂id',
  `attr_key` VARCHAR(64) NOT NULL COMMENT '自定义属性字段',
  `show_name` VARCHAR(64) NULL COMMENT '自定义属性名称',
  `description` VARCHAR(200) NULL COMMENT '描述',
  `is_enable` TINYINT UNSIGNED NULL DEFAULT 1 COMMENT '是否启用',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人\n',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`attr_key`))
COMMENT = '自定义属性配置表';


-- -----------------------------------------------------
-- Table `trace`.`trace_code_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_code_rule` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `rule_name` VARCHAR(64) NULL COMMENT '规则名称',
  `rule_type` TINYINT UNSIGNED NULL COMMENT '规则类型',
  `description` VARCHAR(200) NULL COMMENT '描述',
  `example` VARCHAR(200) NULL COMMENT '测试用例',
  `rule_attr` JSON NULL COMMENT '规则属性',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '删除标记',
  PRIMARY KEY (`id`))
COMMENT = '编码规则表';


-- -----------------------------------------------------
-- Table `trace`.`trace_code_attr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_code_attr` (
  `id` INT NOT NULL COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `parent_id` INT NULL COMMENT '属性父id',
  `attr_key` VARCHAR(64) NULL COMMENT '属性名称',
  `attr_name` VARCHAR(64) NULL COMMENT '属性名称',
  `description` VARCHAR(200) NULL COMMENT '描述',
  `value_type` TINYINT UNSIGNED NULL COMMENT '属性值类型',
  `attr_type` TINYINT UNSIGNED NULL COMMENT '属性类型',
  `create_type` TINYINT UNSIGNED NULL COMMENT '创建类型',
  `use_type` TINYINT UNSIGNED NULL COMMENT '使用类型',
  `extend_attr` JSON NULL COMMENT '扩展属性',
  `created_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '创建人',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_by` VARCHAR(64) NULL DEFAULT 'system' COMMENT '修改人',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` TINYINT UNSIGNED NULL COMMENT '删除标记',
  PRIMARY KEY (`id`))
COMMENT = '编码属性表';


-- -----------------------------------------------------
-- Table `trace`.`trace_code_serial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_code_serial` (
  `id` INT NOT NULL COMMENT '自增id',
  `factory_id` INT NULL COMMENT '工厂id',
  `code_attr_id` INT NULL COMMENT '属性id',
  `reset_attr` VARCHAR(1000) NULL COMMENT '清零属性',
  `increment_attr` VARCHAR(1000) NULL COMMENT '自增属性',
  `serial` INT NULL COMMENT '流水号',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '删除标记',
  PRIMARY KEY (`id`))
COMMENT = '编码流水表';


-- -----------------------------------------------------
-- Table `trace`.`trace_material_flow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trace`.`trace_material_flow` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `op_type` TINYINT NULL COMMENT '操作类型',
  `src_operation_id` BIGINT NULL COMMENT '源业务操作id',
  `dest_operation_id` BIGINT UNSIGNED NULL COMMENT '目标业务操作id',
  `deduction_num` DECIMAL(12,4) NULL COMMENT '扣减数',
  `created_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '物料流转表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
